### ISSUE TITLE
Some thoughts on the minimalist service contract example.

### ISSUE THREAD

**Issue by Vinai** [astorm/service-contract-example#1]
From what I see this is meant to be a minimalist implementation, I'll keep that in mind while commenting.

In the [`webapi.xml`](https://github.com/astorm/service-contract-example/blob/master/etc/webapi.xml#L3) the route should start with a leading slash, that is  
`<route url="/V1/pulsestorm_apitest2/thing" method="GET">`

Naming classes with one word per namespace leaves not very expressive base names when using PHP 5.3 namespaces and class imports.  
For example, `\Pulsestorm\Apitest2\Model\Thing\Repository` would be more easy to find and use in an IDE if it where called `\Pulsestorm\Apitest2\Model\ThingRepository`.   
Using `Model\Thing\Repository` is mostly a leftover from Magento 1 days, where the pseudo namespace always was part of the whole class name, e.g. `...Model_Thing_Repository`.

The PHPDoc annotation `{@inheritdoc}` is only noise unless some more information is added (see https://www.phpdoc.org/docs/latest/guides/inheritance.html).  
If no phpdoc annotation is given, it's the default behavior anyway, so it's better to not have it.  
Outside from examples I've never seen a usecase where it was actually needed.  
I guess my suggestion is to remove it from [the code](https://github.com/astorm/service-contract-example/blob/master/Model/Thing/Repository.php#L6-L8) that is generated.

The [class property `$id`](https://github.com/astorm/service-contract-example/blob/master/Model/Thing.php#L11) is declared dynamically. According to current "best practice" it should be declared as a class property using one of the visibility keywords, like

```php
class Thing implements \Pulsestorm\Apitest2\Api\Data\ThingInterface
{
  /**
   * @var int
   */
   private $id;

   // ...
}
```

In the [`ThingInterface`](https://github.com/astorm/service-contract-example/blob/master/Api/Data/ThingInterface.php#L11-L14) the setter argument type should be specified using a `@param` annotation.

Personally I think returning `void` from a setter is more appropriate than [returning `$this`](https://github.com/astorm/service-contract-example/blob/master/Api/Data/ThingInterface.php#L12), if the expectation is that the object state is changed.  
This is in contrast to immutable objects where setters return a new instance of the object with the new state. This isn't part of any "Magento" standard though, only my personal point of view.

Even though this is a minimalist example, I think it would be good if `ThingRepositoryInterface::get()` would take an `$id` parameter.  
That would also need to be added to the `etc/webapi.xml` file route like `<route url="/V1/pulsestorm_apitest2/thing/:id" method="GET">`  

Maybe the repository could then set the given ID on the `Thing` instance instead of the hardcoded `1`.
In practice it seems most API endpoints have at lease one argument, so this might be a more useful default to start with.  

Instead of instantiating the [`Thing` with `new`](https://github.com/astorm/service-contract-example/blob/master/Model/Thing/Repository.php#L11), the repository should have a `\Pulsestorm\Apitest2\Api\Data\ThingInterfaceFactory` as constructor dependency, and instantiate the `Thing` by calling `$this->thingFactory->create()`.

The `etc/di.xml` file should also contain a `<preference>` mapping the `ThingInterface` to the `Thing` implementation.  

If this example should follow the official Magento 2 best practices (that is "do-as-I-say-not-do-as-I-do"), the data model implementing the Api Data interface should not be the regular ORM model, but rather a separate data model as can be seen in the customer module, where `\Magento\Customer\Model\Data\Customer` implements `CustomerInterface` (vs. `\Magento\Customer\Model\Customer` which only is the CRUD ORM model).  
This still is the official Magento recommendation according to Anton Krill.
Personally I think this is not a very pragmatic approach, but since you asked for feedback I thought I'd add it.

**Comment by astorm** [comment]
Thanks @Vinai -- that's great feedback all around.

Re:

> In the ThingInterface the setter argument type should be specified using a @param annotation.

We'll be adding that `@param` regardless -- but do you know if there's anything in Magento's core code enforces is? i.e. during webapi.xml requests, failure to include the `@param` on a repository method or on an object getter results in an exception being thrown.  Is there anything like that for the data object setters, or are we doing this just for the sake of IDEs and other code parsers?

**Comment by Vinai** [comment]
There is some code in `\Magento\Framework\Reflection\TypeProcessor::getParamType()` that gets called from `\Magento\Framework\Reflection\MethodsMap::getMethodParams()`, but I don't actually think it is technically required for the WebAPI to work.  

That said, I do think it is helpful to specify the expected input and output types of functions in general, ideally by typing the method parameters in the signature, or alternatively using a PHPDoc block, if only as a curtsy to other developers or my future self :)

**Comment by astorm** [comment]
Made most of the suggested adjustments.  The few I've left out are

- return $this
- `Magento\Customer\Model\Data\Customer`

My ultimate intent with the pestle generation command is to let a developer point at a standard Magento CRUD model (still the only supported-ish way to persist data in Magento 2) and have Magento fill-in the service contract boiler plate.  These models have a long history of using setter chains (`->setFoo()->setBar()`), so I'm not comfortable going against so many years of practice (best or otherwise).

Similarly, the completely separate model for `Magento\Customer\Model\Data\Customer` seems a little excessive for our purposes.  I *think* see Magento's reasoning for it -- not having to deal with the CRUD models means not needing to jam a `AbstractExtensibleObject` into the existing object hierarchy.  However, with so much still in flux one less class seems like the right approach for an initial implementation. 

Closing out, but if anyone has more thoughts (or the just committed module seems off) feel free to re-open or open a new issue.
